// Listă statică de orașe din România pentru autocomplete (datalist) pe câmpul „Locație".
// Acoperă toate municipiile + orașe notabile. Sugestie pură UX — câmpul rămâne text liber
// (nu e validat ca enum pe server): userul poate scrie și o comună/sat care nu e în listă.
const CITIES = [
  "București",
  "Cluj-Napoca",
  "Timișoara",
  "Iași",
  "Constanța",
  "Craiova",
  "Brașov",
  "Galați",
  "Ploiești",
  "Oradea",
  "Brăila",
  "Arad",
  "Pitești",
  "Sibiu",
  "Bacău",
  "Târgu Mureș",
  "Baia Mare",
  "Buzău",
  "Botoșani",
  "Satu Mare",
  "Râmnicu Vâlcea",
  "Drobeta-Turnu Severin",
  "Suceava",
  "Piatra Neamț",
  "Târgu Jiu",
  "Târgoviște",
  "Focșani",
  "Bistrița",
  "Tulcea",
  "Reșița",
  "Slatina",
  "Călărași",
  "Alba Iulia",
  "Giurgiu",
  "Deva",
  "Hunedoara",
  "Zalău",
  "Sfântu Gheorghe",
  "Bârlad",
  "Vaslui",
  "Roman",
  "Turda",
  "Mediaș",
  "Slobozia",
  "Alexandria",
  "Voluntari",
  "Lugoj",
  "Medgidia",
  "Onești",
  "Miercurea Ciuc",
  "Sighetu Marmației",
  "Petroșani",
  "Mangalia",
  "Tecuci",
  "Odorheiu Secuiesc",
  "Râmnicu Sărat",
  "Pașcani",
  "Dej",
  "Reghin",
  "Năvodari",
  "Câmpina",
  "Caracal",
  "Săcele",
  "Făgăraș",
  "Fetești",
  "Sighișoara",
  "Borșa",
  "Curtea de Argeș",
  "Sebeș",
  "Huși",
  "Aiud",
  "Câmpulung",
  "Caransebeș",
  "Vulcan",
  "Lupeni",
  "Câmpia Turzii",
  "Carei",
  "Turnu Măgurele",
  "Râșnov",
  "Dorohoi",
  "Vatra Dornei",
  "Rădăuți",
  "Gherla",
  "Blaj",
  "Moinești",
  "Câmpulung Moldovenesc",
  "Comănești",
  "Gheorgheni",
  "Drăgășani",
  "Toplița",
  "Motru",
  "Marghita",
  "Mioveni",
  "Salonta",
  "Roșiori de Vede",
  "Câmpeni",
  "Codlea",
  "Adjud",
  "Băicoi",
  "Buftea",
  "Otopeni",
  "Pantelimon",
  "Sinaia",
  "Bușteni",
  "Predeal",
  "Eforie",
  "Năsăud",
  "Beclean",
  "Cernavodă",
  "Hârșova",
  "Comarnic",
  "Breaza",
  "Mizil",
  "Urziceni",
  "Oltenița",
  "Videle",
  "Bolintin-Vale",
  "Zărnești",
  "Victoria",
  "Avrig",
  "Cugir",
  "Orăștie",
  "Petrila",
  "Brad",
  "Simeria",
  "Bocșa",
  "Oravița",
  "Sânnicolau Mare",
  "Jimbolia",
  "Salonta",
  "Beiuș",
  "Aleșd",
  "Șimleu Silvaniei",
  "Jibou",
  "Cisnădie",
  "Agnita",
  "Târnăveni",
  "Luduș",
  "Sovata",
  "Cristuru Secuiesc",
  "Bălan",
  "Covasna",
  "Târgu Secuiesc",
  "Baraolt",
  "Negrești-Oaș",
  "Tășnad",
  "Vișeu de Sus",
  "Baia Sprie",
  "Cavnic",
  "Seini",
  "Săveni",
  "Flămânzi",
  "Hârlău",
  "Târgu Frumos",
  "Negrești",
  "Murgeni",
  "Buhuși",
  "Dărmănești",
  "Slănic-Moldova",
  "Târgu Neamț",
  "Roznov",
  "Bicaz",
  "Gura Humorului",
  "Fălticeni",
  "Siret",
  "Solca",
  "Liteni",
  "Panciu",
  "Mărășești",
  "Odobești",
  "Nehoiu",
  "Pogoanele",
  "Mizil",
  "Boldești-Scăeni",
  "Plopeni",
  "Urlați",
  "Vălenii de Munte",
  "Băile Govora",
  "Călimănești",
  "Băbeni",
  "Horezu",
  "Brezoi",
  "Ocnele Mari",
  "Bumbești-Jiu",
  "Rovinari",
  "Țicleni",
  "Novaci",
  "Balș",
  "Corabia",
  "Drăgănești-Olt",
  "Scornicești",
  "Băilești",
  "Calafat",
  "Filiași",
  "Segarcea",
  "Dăbuleni",
  "Zimnicea",
  "Roșiori de Vede",
  "Costești",
  "Topoloveni",
  "Ștefănești",
  "Lehliu-Gară",
  "Budești",
  "Fundulea",
  "Țăndărei",
  "Amara",
  "Fierbinți-Târg",
  "Babadag",
  "Isaccea",
  "Măcin",
  "Sulina",
  "Ovidiu",
  "Techirghiol",
  "Murfatlar",
  "Negru Vodă",
  "Băneasa",
];

// Dedup (lista de mai sus are câteva orașe care apar în mai multe contexte) + sortare alfabetică (ro).
export const RO_CITIES: readonly string[] = Array.from(new Set(CITIES)).sort((a, b) =>
  a.localeCompare(b, "ro"),
);
